In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("所有库导入成功！")
print(f"pandas版本: {pd.__version__}")

所有库导入成功！
pandas版本: 2.3.3

In [5]:
import os

# 检查数据文件
data_path = '../data/'
files = os.listdir(data_path)
print("data文件夹中的文件:")
for f in files:
    print(f"  - {f}")

data文件夹中的文件:
  - .gitkeep
  - testA.csv
  - train.csv

In [6]:
import os
data_path = '../data/'
files = os.listdir(data_path)
print("data文件夹中的文件:")
for f in files:
    print(f"  - {f}")

data文件夹中的文件:
  - .gitkeep
  - testA.csv
  - train.csv

In [7]:
train = pd.read_csv('../data/train.csv', sep=' ')
test = pd.read_csv('../data/testA.csv', sep=' ')
print(f"训练集形状: {train.shape}")
print(f"测试集形状: {test.shape}")
print("\n训练集前5行:")
train.head()

训练集形状: (150000, 31)
测试集形状: (50000, 30)

训练集前5行:

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,0,736,20040402,30.0,6,1.0,0.0,0.0,60,12.5,...,0.235676,0.101988,0.129549,0.022816,0.097462,-2.881803,2.804097,-2.420821,0.795292,0.914762
1,1,2262,20030301,40.0,1,2.0,0.0,0.0,0,15.0,...,0.264777,0.121004,0.135731,0.026597,0.020582,-4.900482,2.096338,-1.030483,-1.722674,0.245522
2,2,14874,20040403,115.0,15,1.0,0.0,0.0,163,12.5,...,0.251410,0.114912,0.165147,0.062173,0.027075,-4.846749,1.803559,1.565330,-0.832687,-0.229963
3,3,71865,19960908,109.0,10,0.0,0.0,1.0,193,15.0,...,0.274293,0.110300,0.121964,0.033395,0.000000,-4.509599,1.285940,-0.501868,-2.438353,-0.478699
4,4,111080,20120103,110.0,5,1.0,0.0,0.0,68,5.0,...,0.228036,0.073205,0.091880,0.078819,0.121534,-1.896240,0.910783,0.931110,2.834518,1.923482

In [8]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   01_EDA.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [1]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	01_EDA.ipynb

nothing added to commit but untracked files present (use "git add" to track)

In [2]:
!git add notebooks/01_EDA.ipynb

warning: could not open directory 'notebooks/notebooks/': No such file or directory
fatal: pathspec 'notebooks/01_EDA.ipynb' did not match any files

In [1]:
!git rm --cached 01_EDA.ipynb

fatal: pathspec '01_EDA.ipynb' did not match any files

In [2]:
!dir notebooks

 驱动器 C 中的卷是 OS
 卷的序列号是 3EC6-753B

 C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks 的目录

找不到文件

In [4]:
!cd

C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks

In [5]:
import os
os.chdir(r'C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks')
!dir

 驱动器 C 中的卷是 OS
 卷的序列号是 3EC6-753B

 C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks 的目录

2026/04/01  21:59    <DIR>          .
2026/04/01  20:24    <DIR>          ..
2026/04/01  20:25                 0 .gitkeep
2026/04/01  20:54    <DIR>          .ipynb_checkpoints
2026/04/01  21:59            12,649 01_EDA.ipynb
               2 个文件         12,649 字节
               3 个目录 398,668,857,344 可用字节

In [6]:
import os
os.chdir(r'C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction')
print(os.getcwd())

C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction

In [7]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	notebooks/01_EDA.ipynb

nothing added to commit but untracked files present (use "git add" to track)

In [8]:
!git add notebooks/01_EDA.ipynb

warning: in the working copy of 'notebooks/01_EDA.ipynb', LF will be replaced by CRLF the next time Git touches it

In [9]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   notebooks/01_EDA.ipynb

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   notebooks/01_EDA.ipynb

In [10]:
!git add notebooks/01_EDA.ipynb

warning: in the working copy of 'notebooks/01_EDA.ipynb', LF will be replaced by CRLF the next time Git touches it

In [11]:
!git commit -m "完成EDA分析，添加数据分析代码"

[main 29e230f] 瀹屾垚EDA鍒嗘瀽锛屾坊鍔犳暟鎹�鍒嗘瀽浠ｇ爜
 1 file changed, 594 insertions(+)
 create mode 100644 notebooks/01_EDA.ipynb

In [12]:
!git push

To https://github.com/jiawen-yu/tianchi-price-predicition
   139b6e2..29e230f  main -> main

In [10]:
print("\n测试集前5行:")
test.head()

测试集前5行:

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,150000,66932,20111212,222.0,4,5.0,1.0,1.0,313,15.0,...,0.264405,0.121800,0.070899,0.106558,0.078867,-7.050969,-0.854626,4.800151,0.620011,-3.664654
1,150001,174960,19990211,19.0,21,0.0,0.0,0.0,75,12.5,...,0.261745,0.000000,0.096733,0.013705,0.052383,3.679418,-0.729039,-3.796107,-1.541230,-0.757055
2,150002,5356,20090304,82.0,21,0.0,0.0,0.0,109,7.0,...,0.260216,0.112081,0.078082,0.062078,0.050540,-4.926690,1.001106,0.826562,0.138226,0.754033
3,150003,50688,20100405,0.0,0,0.0,0.0,1.0,160,7.0,...,0.260466,0.106727,0.081146,0.075971,0.048268,-4.864637,0.505493,1.870379,0.366038,1.312775
4,150004,161428,19970703,26.0,14,2.0,0.0,0.0,75,15.0,...,0.250999,0.000000,0.077806,0.028600,0.081709,3.616475,-0.673236,-3.197685,-0.025678,-0.101290

In [14]:
import os
print("当前目录:", os.getcwd())
!dir

当前目录: C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks
 驱动器 C 中的卷是 OS
 卷的序列号是 3EC6-753B

 C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks 的目录

2026/04/02  09:31    <DIR>          .
2026/04/01  20:24    <DIR>          ..
2026/04/01  20:25                 0 .gitkeep
2026/04/01  20:54    <DIR>          .ipynb_checkpoints
2026/04/02  09:31            25,988 01_EDA.ipynb
               2 个文件         25,988 字节
               3 个目录 395,061,919,744 可用字节

In [15]:
!dir notebooks

 驱动器 C 中的卷是 OS
 卷的序列号是 3EC6-753B

 C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks 的目录

找不到文件

In [16]:
!dir *.ipynb

 驱动器 C 中的卷是 OS
 卷的序列号是 3EC6-753B

 C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction\notebooks 的目录

2026/04/02  09:33            26,092 01_EDA.ipynb
               1 个文件         26,092 字节
               0 个目录 395,055,263,744 可用字节

In [17]:
import os
os.chdir(r'C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction')
print("当前目录:", os.getcwd())

当前目录: C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction

In [18]:
!dir

 驱动器 C 中的卷是 OS
 卷的序列号是 3EC6-753B

 C:\Users\yjw10\OneDrive\桌面\tianchi-price-prediction 的目录

2026/04/01  20:24    <DIR>          .
2026/04/01  20:08    <DIR>          ..
2026/04/01  20:20               124 .gitignore
2026/04/01  21:05    <DIR>          data
2026/04/02  09:33    <DIR>          notebooks
2026/04/01  20:25    <DIR>          output
2026/04/02  09:20             1,469 README.md
2026/04/01  20:26    <DIR>          report
2026/04/01  20:21               118 requirements.txt
2026/04/01  20:26    <DIR>          src
               3 个文件          1,711 字节
               7 个目录 395,041,415,168 可用字节